// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNFnLMssmjYVR34jyxzvJL1GyVBr_c_wM',
    appId: '1:215188652815:web:6dffeba840a9fdc157347a',
    messagingSenderId: '215188652815',
    projectId: 'hasarharitasi',
    authDomain: 'hasarharitasi.firebaseapp.com',
    storageBucket: 'hasarharitasi.appspot.com',
    measurementId: 'G-E62X5LRVEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpAQxXtrfB8kBRKgt3MFndOoCwRPF47LM',
    appId: '1:215188652815:android:0529700b7eb49b1857347a',
    messagingSenderId: '215188652815',
    projectId: 'hasarharitasi',
    storageBucket: 'hasarharitasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLkBuufWyTSW2yUuiUjZwhfsecm9FccU',
    appId: '1:215188652815:ios:9d5f7da0ec353c8a57347a',
    messagingSenderId: '215188652815',
    projectId: 'hasarharitasi',
    storageBucket: 'hasarharitasi.appspot.com',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLkBuufWyTSW2yUuiUjZwhfsecm9FccU',
    appId: '1:215188652815:ios:9b80fbbe4ccbef6557347a',
    messagingSenderId: '215188652815',
    projectId: 'hasarharitasi',
    storageBucket: 'hasarharitasi.appspot.com',
    iosBundleId: 'com.example.deneme.RunnerTests',
  );
}
